### ISSUE TITLE
ValkyrieRepository race condition

### ISSUE THREAD

**Issue by general-failure** [cmadsen/Valkyrie-RCP#21] opened 2015-01-11 14:12 UTC
ValkyrieRepository must have been initialized in the spring context before any ActionCommand as they call ValkyrieRepository.getInstance()... via the constructor / afterPropertiesSet(). Otherwise, ValkyrieRepository.getInstance() will hang on the latch.
The test suite actually hangs on the latch on some occasions.
Currently I have no idea for a solution myself. Don't know if there are some clever container tricks, e.g. load a minimal ValkyrieRepository context first and then add the "main" context as a child context to that or something similar in that direction.

**Comment by lievendoclo** [comment] 2015-01-11 17:31
I encountered this one some time ago as well but couldn't find the cause. Thanks for letting me know, I'll have a look this evening.

**Comment by lievendoclo** [comment] 2015-01-11 21:19
fixed in master

**Closed by lievendoclo** 2015-01-11 21:19 UTC
